Adding init.d script

diff --git a/contrib/init.d/fogbow-opportunism b/contrib/init.d/fogbow-opportunism
--- a/contrib/init.d/fogbow-opportunism
+++ b/contrib/init.d/fogbow-opportunism
@@ -1,3 +1,121 @@
-#!/bin/bash
-export PYTHONPATH=/var/lib/fogbow-opportunism/lib
-/var/lib/fogbow-opportunism/bin/powernapd
+#! /bin/sh
+### BEGIN INIT INFO
+# Provides:          fogbow-opportunism
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: Starts the fogbow-opportunism module of Fogbow(fogbowcloud.org)
+### END INIT INFO
+
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="Starts the fogbow-opportunism module of Fogbow(fogbowcloud.org)"
+NAME=fogbow-opportunism
+DAEMON_BASE=/var/lib/fogbow-opportunism
+DAEMON_LIB=$DEAMON_BASE/lib
+DAEMON=$DAEMON_BASE/bin/powernapd
+DAEMON_ARGS="start"
+PIDPATH=/var/run/fogbow-opportunism
+SCRIPTNAME=/etc/init.d/$NAME
+PUSER=fogbow
+
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
+
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
+. /lib/lsb/init-functions
+
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	export PYTHONPATH=$DEAMON_BASE
+	mkdir -p $PIDPATH
+	chown -R fogbow:fogbow $PIDPATH
+	start-stop-daemon --start --quiet --chuid $PUSER --exec $DAEMON --pidfile $PIDPATH/$NAME.pid --test > /dev/null \
+		|| return 1
+	start-stop-daemon --start --quiet --chuid $PUSER --exec $DAEMON -- \
+		$DAEMON_ARGS \
+		|| return 2
+}
+
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	start-stop-daemon --start --quiet --chuid $PUSER --exec $DAEMON stop
+	RETVAL="$?"
+	[ "$RETVAL" = 2 ] && return 2
+	
+    for PIDFILE in `ls $PIDPATH/$NAME*.pid`; do
+    	start-stop-daemon --stop --quiet --oknodo --retry=0/5/KILL/5 --pidfile $PIDFILE 
+    	rm -f $PIDFILE
+    done
+
+	return "$RETVAL"
+}
+
+case "$1" in
+  start)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	do_start
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
+  stop)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
+  status)
+       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+       ;;
+ #reload|force-reload)
+  restart|force-reload)
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+	  	# Failed to stop
+		log_end_msg 1
+		;;
+	esac
+	;;
+  *)
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	exit 3
+	;;
+esac
+
+:
